apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: avg4yhzlk-nodejs 
  janus-idp.io/tekton: avg4yhzlk-nodejs
  backstage.io/kubernetes-id: avg4yhzlk-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: avg4yhzlk-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml