apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: avg4yhzlk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: avg4yhzlk-nodejs 
  name: avg4yhzlk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: avg4yhzlk-nodejs 
